// ============================================================
// URL HELPERS - query string parsing / serialization
// ============================================================
// Used by the RequestBuilder Params tab (FRONTEND_PLAN.md 1.2).
//
// Both helpers work on the raw URL string instead of `new URL()` so a
// relative or half-typed URL can never throw, and serialization goes
// through the standard URLSearchParams API for correct encoding
// (spaces -> +, &, = escaped, etc.).
// ============================================================

import type { AuthConfig, FormField, QueryParam, RequestBodyType } from "./types";
import type { Header } from "./types";

/** Split a URL into base (no query, no hash), query string, and hash. */
function splitUrl(rawUrl: string): {
  base: string;
  query: string;
  hash: string;
} {
  const hashStart = rawUrl.indexOf("#");
  const hash = hashStart === -1 ? "" : rawUrl.slice(hashStart);
  const withoutHash = hashStart === -1 ? rawUrl : rawUrl.slice(0, hashStart);

  const queryStart = withoutHash.indexOf("?");
  if (queryStart === -1) {
    return { base: withoutHash, query: "", hash };
  }
  return {
    base: withoutHash.slice(0, queryStart),
    query: withoutHash.slice(queryStart + 1),
    hash,
  };
}

/**
 * Parse the query string of a URL into Params-tab rows.
 * Returns [] when the URL has no query (or an empty one).
 */
export function parseQueryParams(rawUrl: string): QueryParam[] {
  const { query } = splitUrl(rawUrl);
  if (query === "") return [];

  return Array.from(new URLSearchParams(query).entries()).map(
    ([key, value], index) => ({
      // Deterministic ids: while the user types in the URL bar the rows
      // are re-parsed on every keystroke, and stable keys let React reuse
      // the same DOM nodes (a remount mid-click would swallow the click).
      id: `qp-${index}-${key}`,
      key,
      value,
      enabled: true,
    })
  );
}

/**
 * Return `rawUrl` with its query string replaced by the enabled,
 * non-empty params: the plan's `?key=value&key2=value2` append.
 *
 * Replacing (rather than blindly appending) is what keeps the history
 * round-trip safe: a sent URL already contains its query string, so
 * reloading it and re-sending must not produce `?a=1?a=1`.
 * Duplicate keys between rows are preserved (URLSearchParams.append).
 */
export function buildUrlWithParams(rawUrl: string, params: QueryParam[]): string {
  const { base, hash } = splitUrl(rawUrl);

  const search = new URLSearchParams();
  for (const param of params) {
    if (param.enabled && param.key.trim() !== "") {
      search.append(param.key, param.value);
    }
  }

  const query = search.toString();
  return query ? `${base}?${query}${hash}` : `${base}${hash}`;
}

/**
 * Fresh boundary for a multipart/form-data request. The same value goes
 * into the auto-set `Content-Type: multipart/form-data; boundary=...`
 * header and into buildMultipartBody(), so header and body always agree.
 */
export function makeFormBoundary(): string {
  return `----ApiPulseBoundary${crypto.randomUUID()}`;
}

/**
 * Serialize enabled fields into a multipart/form-data body (RFC 7578).
 *
 * Done manually instead of via FormData so the result is a plain string
 * that can be stored in history and re-sent verbatim later. Text fields
 * only - file fields are covered by the Binary body type.
 */
export function buildMultipartBody(
  fields: FormField[],
  boundary: string
): string {
  const parts = fields
    .filter((field) => field.enabled && field.key.trim() !== "")
    .map((field) => {
      // Field names are quoted-string parameters: escape quotes and drop
      // CR/LF. Field values are raw octets terminated only by the
      // (unique) boundary, so they need no escaping.
      const name = field.key.replace(/[\r\n]/g, "").replace(/"/g, '\\"');
      return `--${boundary}\r\nContent-Disposition: form-data; name="${name}"\r\n\r\n${field.value}\r\n`;
    });

  return parts.join("") + `--${boundary}--\r\n`;
}

/**
 * Best-effort body type when reloading a request from history (plan 1.4).
 * The chosen type itself isn't persisted - only the final body string and
 * the Content-Type header are - so infer: empty -> None, parseable JSON
 * -> JSON, anything else -> Raw (which resends the string verbatim).
 */
export function inferBodyType(body: string): RequestBodyType {
  if (body === "") return "none";
  try {
    JSON.parse(body);
    return "json";
  } catch {
    return "raw";
  }
}

/**
 * Base64 payload for `Authorization: Basic ...` (plan 2.1).
 * Text is UTF-8 encoded first because btoa() only accepts Latin1 and
 * throws on unicode passwords (e.g. "pässwörd").
 */
function toBase64(value: string): string {
  return btoa(String.fromCharCode(...new TextEncoder().encode(value)));
}

/** Fixed React key for the header generated by the Auth tab. */
const AUTH_HEADER_ID = "auth-header";

/**
 * Build the header the Auth tab injects when the request is sent
 * (plan 2.1: "Auto-add Authorization header"), or null when auth is off
 * or the required fields are still empty.
 *
 * Pure and separate from RequestBuilder's state so the Auth tab can show
 * a live preview of exactly what will be added on send.
 */
export function buildAuthHeader(auth: AuthConfig): Header | null {
  switch (auth.type) {
    case "none":
      return null;
    case "bearer": {
      const token = auth.token.trim();
      if (token === "") return null;
      return {
        id: AUTH_HEADER_ID,
        key: "Authorization",
        value: `Bearer ${token}`,
        enabled: true,
      };
    }
    case "basic": {
      if (auth.username === "" && auth.password === "") return null;
      return {
        id: AUTH_HEADER_ID,
        key: "Authorization",
        value: `Basic ${toBase64(`${auth.username}:${auth.password}`)}`,
        enabled: true,
      };
    }
    case "api-key": {
      const key = auth.apiKeyName.trim();
      const value = auth.apiKeyValue.trim();
      if (key === "" || value === "") return null;
      return { id: AUTH_HEADER_ID, key, value, enabled: true };
    }
  }
}

/**
 * Merge the auth-generated header into the headers that will be sent
 * (plan 2.1). Auth wins: enabled user headers with the same name are
 * dropped first, so a stored/manual Authorization header can never clash
 * with (or duplicate) the active auth config.
 */
export function applyAuthHeader(headers: Header[], auth: AuthConfig): Header[] {
  const authHeader = buildAuthHeader(auth);
  if (authHeader === null) return headers;

  const authKey = authHeader.key.trim().toLowerCase();
  return [
    ...headers.filter((h) => h.key.trim().toLowerCase() !== authKey),
    authHeader,
  ];
}